DROP TABLE IF EXISTS title CASCADE;
DROP TABLE IF EXISTS Release Date CASCADE;
DROP TABLE IF EXISTS developer CASCADE;
DROP TABLE IF EXISTS publisher CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS Product Rating CASCADE;
DROP TABLE IF EXISTS User Score CASCADE;
DROP TABLE IF EXISTS User Ratings Count CASCADE;
--
DROP TABLE IF EXISTS Accounts;
--
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Customers;
